# Generated by Django 6.1.1 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=50)),
                ('rarity', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=0)),
                ('atk_base', models.IntegerField(default=0)),
                ('atk_max', models.IntegerField(default=0)),
                ('hp_base', models.IntegerField(default=0)),
                ('hp_max', models.IntegerField(default=0)),
                ('param_str', models.CharField(default='E', max_length=10)),
                ('param_end', models.CharField(default='E', max_length=10)),
                ('param_agi', models.CharField(default='E', max_length=10)),
                ('param_mna', models.CharField(default='E', max_length=10)),
                ('param_lck', models.CharField(default='E', max_length=10)),
                ('param_np', models.CharField(default='E', max_length=10)),
                ('face_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
