# Generated by Django 6.1.1 on 2026-09-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servant',
            name='alignment',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='servant',
            name='art_stage1',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='art_stage2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='art_stage3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='art_stage4',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='attribute',
            field=models.CharField(default='Earth', max_length=20),
        ),
        migrations.AddField(
            model_name='servant',
            name='deck',
            field=models.CharField(default='QABBB', max_length=10),
        ),
        migrations.AddField(
            model_name='servant',
            name='np_card',
            field=models.CharField(default='Buster', max_length=20),
        ),
        migrations.AddField(
            model_name='servant',
            name='np_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='np_type',
            field=models.CharField(default='Anti-Unit', max_length=50),
        ),
    ]
