# Generated by Django 5.0.2 on 2026-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servants', '0002_servant_alignment_servant_art_stage1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servant',
            name='active_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servant',
            name='np_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servant',
            name='passive_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servant',
            name='profile_lore',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='servant',
            name='deck',
            field=models.CharField(default='QAABB', max_length=10),
        ),
        migrations.AlterField(
            model_name='servant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
