# Generated by Django 6.1.1 on 2026-09-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servants', '0003_servant_active_skills_servant_np_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servant',
            name='atlas_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
