# Generated by Django 6.1.1 on 2026-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servants', '0004_servant_atlas_id_alter_servant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servant',
            name='battery_party',
            field=models.IntegerField(default=0, help_text='Total party-wide NP battery at skill level 10'),
        ),
        migrations.AddField(
            model_name='servant',
            name='battery_self',
            field=models.IntegerField(default=0, help_text='Total personal self battery at skill level 10'),
        ),
        migrations.AddField(
            model_name='servant',
            name='battery_target',
            field=models.IntegerField(default=0, help_text='Total targeted ally NP battery at skill level 10'),
        ),
    ]
